# -*- coding: utf-8 -*-
"""basic EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10JS9Id40yUOtrOM2r1AVnVGuHS2yhjGQ
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

data = pd.read_csv('student-por.csv')

data.head(5)

from google.colab import drive
drive.mount('/content/drive')

data.info

data.info()

f, ax = plt.subplots(figsize=(4, 4))
plt.pie(data['sex'].value_counts().tolist(), 
        labels=['Female', 'Male'], colors=['#ffd1df', '#a2cffe'], 
        autopct='%1.1f%%', startangle=-90)
axis = plt.axis('equal')

data = pd.read_csv('student-por.csv')
f, ax = plt.subplots(figsize=(8, 8))
sns.set_style('whitegrid')
ax= sns.boxplot(x='sex',y='age',data=data)
ax = sns.stripplot(x="sex", y="age",data=data)

import seaborn as sns
fig, ax = plt.subplots(figsize=(5, 4))
sns.histplot(data['age'])
ax = ax.set(ylabel="Count", xlabel="Age")

f, ax = plt.subplots(figsize=(4, 4))
plt.pie(data['studytime'].value_counts().tolist(), 
        labels=['2 to 5 hours', '<2 hours', '5 to 10 hours', '>10 hours'], 
        autopct='%1.1f%%', startangle=90)
axis = plt.axis('equal')

f, ax = plt.subplots(figsize=(4, 4))
plt.pie(data['romantic'].value_counts().tolist(), 
        labels=['No', 'Yes'], autopct='%1.1f%%', startangle=90)
axis = plt.axis('equal')

new_data = data.rename(columns = {"Pstatus": "cohabStatus",
                                  "famsup":"educationalSupport",
                                  "famrel": "famRelations"})
new_data.info()

groupedData = new_data.groupby('school')
groupedData.first()

f, ax = plt.subplots(figsize=(8, 8))
sns.set_style('whitegrid')
ax= sns.boxplot(x='school',y='age',data=data)
ax = sns.stripplot(x="school", y="age",data=data)

plot1 = sns.factorplot(x="Walc", y="health", hue="sex", data=data)
plot1.set(ylabel="Health", xlabel="Weekend Alcohol Consumption")

plot2 = sns.factorplot(x="Dalc", y="health", hue="sex", data=data)
plot2.set(ylabel="Health", xlabel="Workday Alcohol Consumption")

plot1 = sns.factorplot(x="G3", y="Walc", data=data)
plot1.set(ylabel="Final Grade", xlabel="Weekend Alcohol Consumption")

plot2 = sns.factorplot(x="G3", y="Dalc", data=data)
plot2.set(ylabel="Final Grade", xlabel="Workday Alcohol Consumption")

fig, ax = plt.subplots(figsize=(5, 4))
sns.distplot(data['Walc'],  
             hist_kws={"alpha": 1, "color": "#a2cffe"}, 
             kde=False, bins=4)
ax = ax.set(ylabel="Students", xlabel="Weekend Alcohol Consumption")

#df = seaborn.load_dataset('tips')
# pairplot with hue sex
sns.pairplot(data, hue ='sex')
# to show
plt.show()

sns.pairplot(data, hue ='age')
# to show
plt.show()

